travis:
  secure:
    BINSTAR_TOKEN: pywYE8nzvK2ZPNajOBdp4XtqSfu5GBaaSFL9lexDWdNn+4zjqmdD+nd/Z6SqfS6p5LC9AqqXCP34lHvDJYOT9x3Bf0nzhIOpbSwDgvf0+Uirsgtur/kNduP9mJSMf6CLy1mjEv0v7tlqcXab2V6GEpuabc/+z7v/EU3oENVtCEDERkovvWOgvAqEy0Bxp5xdHYSkYabxirvD85jcRp0Lxtn0t20VPRJiD5A4sO8pyN5nvRyYJOWPFdDzEj0SbCn+/V3g/t8uKwY3VqpgwfFIDg7M0lFVjXQeRvbRZgjYHwqSHPcePwe1YYX1uNqYNKVIw3kC6D56MCXtiMCQNCaDD/s77E6wArfqeGYX2vu4EfzHw60uS+wfAygeQX+6tZUYJIUKvOnC7l8bf5xAO6LEoBdkrBODNE6WDWmeWd9iF/lB9lQpWSlN+oQULsO97xrEgtQCxAruXFm/jXMpFYBaGSd8lhgyyzd6bkrO3KtbgFDa8Ka/fZ2lfWJUSoRfNU1zq7CpGUIOWiZh67AeYDTVburdSjNV/73VKGDWx576kxB1JxvrAbzQc5n7bGA+4BM5Djt+toUcDEySkr5X5pfiRHJs6UAVDOsbs2f7kOVf6wTMeIrzCYY7idIXX1SMQhafRh1wl3WTjDDxdg5Z//FKHRb3c7EpCRM6TgtVofFwlrk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
